services:

  - type: web
    name: chat-house-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free

    healthCheckPath: /up

    envVars:

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: LOG_LEVEL
        value: error

      - key: QUEUE_CONNECTION
        value: database

      - key: BROADCAST_CONNECTION
        value: reverb